### ISSUE TITLE
Recursive loot scaling

### ISSUE THREAD

**Issue by muon-rw** [ZsoltMolnarrr/PowerScale#10]
Items that get “passed through” multiple loot tables seem to have their bonuses applied for each loot table, instead of once at the end. This presents tremendous balancing issues for modpacks.

Example:
Attack damage scaling per level for difficulty type: .13
Difficulty level: 12
Resulting modifier: `multiply` operation of 1.56 (damage*2.56)

`structory_towers:chests/end_tower` includes loot rolls from `end_city_treasure`, but does not have any diamond swords in its own loot table. 

- Base Diamond Sword: **6** damage
- `end_city_treasure` Diamond Sword: **15.5** damage
- `structory_towers:chests/end_tower` Diamond sword: **39.5** damage

.

(It also seems weapons from the mod Farmers Delight get multiplied twice *per loot table*, which I assume is why they are blacklisted by default)

**Comment by muon-rw** [comment]
The Farmer’s Delight knives part of this may just be the same issue as the first. I realized it may have just been due to the way its loot table inject worked adding another layer where the stats gets multiplied again.

**Comment by ZsoltMolnarrr** [comment]
Feel free to reopen in case new version doesn't resolve this.
