### ISSUE TITLE
Mobs placed as part of structure NBT not scaled

### ISSUE THREAD

**Issue by muon-rw** [ZsoltMolnarrr/PowerScale#12]
Piglin Brutes in the vanilla Bastion remnants, as well as any other mob added as part of structure NBT (mod example: zombies and skeletons inside When Dungeons Arise’ Mushroom Mines), do not have their attributes modified, even if that structure_id is specified in a difficulty type.

In modpack Medieval MC Fabric v21HF
dungeon_difficulty-2.0.3+1.19

**Comment by ZsoltMolnarrr** [comment]
Feel free to reopen if the issue resurfaces in newer versions.
