### ISSUE TITLE
[BUG]The configuration file cannot be modified

### ISSUE THREAD

**Issue by GRAINALCOHOL** [ZsoltMolnarrr/PowerScale#17]
Mod version 2.0.5, game version 1.19.2, loader Fabric, appears to launch the game will restore "dungeon_difficulty_v2.json", so that any changes before the game are invalid (machine translation)

**Comment by ZsoltMolnarrr** [comment]
Did you read the top of the config file with the disclaimer?

**Comment by GRAINALCOHOL** [comment]
Sorry, my native language is not English, I didn't notice the text there
