### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'powerscale'!

### ISSUE THREAD

**Issue by Auscobe** [ZsoltMolnarrr/PowerScale#2]
[crash-2022-09-11_23.01.59-client.txt](https://github.com/ZsoltMolnarrr/PowerScale/files/9544484/crash-2022-09-11_23.01.59-client.txt)
This crash occurs even if the only mods loaded are Fabric API (using 0.53.4), Powerscale (1.0.4), and ProjectileDamageAttribute (1.0.7). Using Fabric Loader 0.14.9.

Please help. I'd really like to use this mod.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Please update your Fabric API to the latest available for 1.18.2 (0.58).

**Comment by Auscobe** [comment]
Thank you very much, that worked. That's the last thing I expected xP
