### ISSUE TITLE
[Feature Request] Expanded zone matching

### ISSUE THREAD

**Issue by OarisHunter** [ZsoltMolnarrr/PowerScale#25]
Maybe these should be separate issues? if so I apologize.

Creating a config file for a heavily modded world gen is very tedious, as such I propose the following
- Structure matching regex (idea being all structures could be matched in dimensions easily, or all village types could fall under 1 match)
- Biome matching by temperature
- Biome matching by elevation (for caves, not sure what the difficulty of this would be like)

**Comment by OarisHunter** [comment]
an alternate idea if true regex isnt feasible for whatever reason: a wildcard character (like sql), i.e. "repurposed_structures:mansion_%" would match all the variations (birch, desert, etc) for that the mansions in that mod.

**Comment by OarisHunter** [comment]
and as a final idea, even just making the structure id field a list would cut down on config management significantly, but I would consider this the worst option

**Comment by ZsoltMolnarrr** [comment]
Hello this features are already implemented.
Take a look at the latest version for 1.21.1.
Structures can be matched by regex or tag.
Biomes can be matched by regex or tag.

Config file have been massively simplified due to these powerful selectors.
