### ISSUE TITLE
Changing "experience multiplier" in config doesn't take effect.

### ISSUE THREAD

**Issue by nonmanners** [ZsoltMolnarrr/PowerScale#3]
1.19.2 Fabric is being used.

Other configuration values ​​are applied, but the option for experience multiplier is not applied.

He told me to register an issue on github, so I registered.

**Comment by nonmanners** [comment]
I will attach part of the config.



 {

  "meta": {
    "comment": "IMPORTANT! Make sure to set `override_with_default` to `false` to allow customization of the config",
    "override_with_default": false,
    "sanitize_config": true,
    "rounding_unit": 0.5
  },
  "perPlayerDifficulty": {
    "entities": [
      {
        "entity_matches": {
          "attitude": "ANY",
          "entity_id_regex": "twilightforest"
        },
          "attributes": [
            {
            "attribute": "generic.max_health",
            "value": 1.5
          }
        ],
          "experience_multiplier": 1.5
      }
    ]
  },
  "dimensions": [
    {
      "world_matches": {
        "dimension_regex": "minecraft:overworld"
      },
      "entities": [
        {
          "entity_matches": {
            "attitude": "ANY",
            "entity_id_regex": "skeleton"
          },
          "attributes": [
            {
              "attribute": "projectile_damage:generic",
              "operation": "ADD",
              "randomness": 0.0,
              "value": -1.5
            }
          ],
          "experience_multiplier": 1.0
        }

**Comment by ZsoltMolnarrr** [comment]
Fixed in v2.0
