### ISSUE TITLE
1.18.2 crash on startup with optifabric

### ISSUE THREAD

**Issue by inkyarev** [ZsoltMolnarrr/PowerScale#4]
[latestlog.txt](https://github.com/ZsoltMolnarrr/DungeonDifficulty/files/10725769/latestlog.txt)

**Comment by ZsoltMolnarrr** [comment]
Hello!
I am sorry I have to close this ticket for multiple reason:
- Optifine never was supported, I recommned using Sodium + Iris for superior performance and compatibility
- The support for 1.18.2 versions has been long expired, please update to 1.19.2 or later version
