### ISSUE TITLE
Null Pointer Exception in Mob Spawner custom rule set causing server wide crash.

### ISSUE THREAD

**Issue by JaceTheGrayOne** [ZsoltMolnarrr/PowerScale#7]
Placing a Mob Spawner in world results in a server crash due to a Null Pointer Exception when the server attempts to invoke the Mob Spawner Entry class _1952.method_38093. This results in a block entity ticking error. Removing the mod resolves this issue and removing the offending spawner then re-installing the mod works as well. 
[crash-2023-04-22_03.33.35-server.txt](https://github.com/ZsoltMolnarrr/DungeonDifficulty/files/11300618/crash-2023-04-22_03.33.35-server.txt)

**Comment by ZsoltMolnarrr** [comment]
Should be fixed by 2.0.2
